# Generated by Django 5.2.4 on 2025-07-04 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male'), ('child', 'child')], default='female', max_length=10),
        ),
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.IntegerField(default=30, max_length=10),
        ),
    ]
