# Generated by Django 5.2.4 on 2025-07-08 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_product_gender_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('female', 'female'), ('male', 'male')], default='female', max_length=10),
        ),
    ]
